Homework 7
IrinaLysenko21/food-delivery-server-goit pull request #5
Opened 2019-11-24 18:03 UTC by IrinaLysenko21

2019-11-25 14:29 UTC, odykyi commented on src/auth/controllers/auth_login.js
> +    expiresIn: 60 * 60 * 24
move this magic number to config 

https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

2019-11-25 14:30 UTC, odykyi commented on src/auth/controllers/auth_register.js
> +    expiresIn: 60 * 60 * 24
the same

2019-11-25 14:30 UTC, odykyi commented on src/config.js
> +  secret: "secret-key"
secret-key ?

change this

2019-11-25 14:31 UTC, odykyi commented on src/users/user_schema.js
> +    required: true
add validation for email

2019-11-25 14:32 UTC, IrinaLysenko21 commented on src/config.js
> +  secret: "secret-key"
это было в демо, на что нужно поменять?

2019-11-25 14:32 UTC, odykyi requested changes
comments

2019-11-27 09:24 UTC, odykyi approved these changes

2019-11-28 10:30 UTC, merged